db:
  username: postgres
  password: root
  pool.size: 12
  driver: PostgresDriver
  url: jdbc:postgresql://localhost:5432/postgres
  hosts: localhost,127.0.0.1
  spring.profiles.active: prod
  properties:
      first: 1
      last: 2
      key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20

logging:
  level:
    root: INFO
  file:
    name: log
    path: /