db:
  username: postgres
  password: root
  driver: PostgresDriver
  url: jdbc:postgresql://localhost:5432/springdata
  hosts: localhost,127.0.0.1
  pool:
    size: 10
    timeout: 20



logging:
  level:
    root: WARN
    by.artem.spring.database.repository.pool: INFO
  file:
    name: log
    path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl: validate




